"""
VCMusicBot — Premium Telegram Voice Chat Music Bot
Author: Generated by Lovable
"""
import os
import logging
from dotenv import load_dotenv

load_dotenv()

logging.basicConfig(
    format="[%(asctime)s] %(levelname)s | %(name)s | %(message)s",
    level=logging.INFO,
)
logging.getLogger("pyrogram").setLevel(logging.WARNING)
logging.getLogger("pytgcalls").setLevel(logging.WARNING)
LOGGER = logging.getLogger("VCMusicBot")

# ── ENV ──────────────────────────────────────────────
API_ID         = int(os.getenv("API_ID", "35828291"))
API_HASH       = os.getenv("API_HASH", "c025ee9d01d73b9d738d4f3e5e6137e2")
BOT_TOKEN      = os.getenv("BOT_TOKEN", "8706213644:AAGXyijPKrhpv6jEmYcSrGOsaPS2WTk2xg4")
SESSION_STRING = os.getenv("SESSION_STRING", "BQIiskMAGVco2ViKdRvOscg3qIv5mWPfZSRcESHJmqWi33OA7NkNNbqkK71YNxUZwbTbk0Y-XJRHZ1wFEP3dPPNJkiKBwklOkE9g_NjNLgkus09rqeoY0BMVMHAHIDd9CYhzgBrobyL5SljKoV1jcDjqTYsDDvZH7xJV2viQkC6InzPgxI2UZ0ltoqE-0o1_6pDMpyDlngGzpZhU0-vZWBHBaWK9ew1jylTmbmS57oPfNUbdO25tQlVjSADsHLgA4Kqd-HeeNWdzD8um3EQcYzO2Id3M_bFjEGhwbXYuYtDguUS6ZRbNrs6XS3lPfcaubk2VLcC5X-0hr7AY16zJdbRgSsM3cQAAAAIG7kcMAQ")
OWNER_ID       = int(os.getenv("OWNER_ID", "7953454559") or 0)
SUPPORT_URL    = os.getenv("SUPPORT_URL", "https://t.me/+K_QvCsPtHPNkNTdl")

if not all([API_ID, API_HASH, BOT_TOKEN, SESSION_STRING]):
    raise SystemExit(
        "❌ Missing env vars. Please set API_ID, API_HASH, BOT_TOKEN, SESSION_STRING."
    )

# Folders
BASE_DIR      = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR    = os.path.join(BASE_DIR, "assets")
DOWNLOADS_DIR = os.path.join(os.getcwd(), "downloads")
os.makedirs(DOWNLOADS_DIR, exist_ok=True)

START_IMAGE = os.path.join(ASSETS_DIR, "start.jpg")

# ── Clients ──────────────────────────────────────────
from pyrogram import Client
from pytgcalls import PyTgCalls

bot = Client(
    "VCMusicBot",
    api_id=API_ID,
    api_hash=API_HASH,
    bot_token=BOT_TOKEN,
    in_memory=True,
)

assistant = Client(
    "VCAssistant",
    api_id=API_ID,
    api_hash=API_HASH,
    session_string=SESSION_STRING,
    in_memory=True,
)

calls = PyTgCalls(assistant)
