"""
VCMusicBot — Premium Telegram Voice Chat Music Bot
Author: Generated by Lovable
"""
import os
import logging
from dotenv import load_dotenv

load_dotenv()

logging.basicConfig(
    format="[%(asctime)s] %(levelname)s | %(name)s | %(message)s",
    level=logging.INFO,
)
logging.getLogger("pyrogram").setLevel(logging.WARNING)
logging.getLogger("pytgcalls").setLevel(logging.WARNING)
LOGGER = logging.getLogger("VCMusicBot")

# ── ENV ──────────────────────────────────────────────
API_ID         = int(os.getenv("API_ID", "35828291"))
API_HASH       = os.getenv("API_HASH", "c025ee9d01d73b9d738d4f3e5e6137e2")
BOT_TOKEN      = os.getenv("BOT_TOKEN", "8638349211:AAGDrEDik3dHtLZr1nsFmmLmHOPN1G-3FTY")
SESSION_STRING = os.getenv("SESSION_STRING", "BQIiskMAJwUwvk3daMUV9CxDRHw2vpHlcQ6AjXoz4EViW1zKP9rE4-ZwoSZPghw15OKo3g9mj5REtvBlUm3ydCAyKhSfYjX5Y1_0y30WTF4ct7muDlwsORJlRGcoB0Zly7a8mMox3SlTRTZNGyea72bfw5TYoUA_xHNI7RMAL_kG63tDi70zpQq9revXSuXC5G-T6U0ILqJZ9vOJhRaQsHbqu2sLBo0ZQC3UCBjO7HcLj93t6cC_o2vtpc8foYwM4gve8O5Id1dHp8iXSnS7WiGDRKv7sQbbhT7EeBHET1-2EhHNLpF6WkkUiF7uQ0ogmPZU0h41ScdOL3L1U9ZvJNk1W3niEQAAAAIC4r-bAQ")
OWNER_ID       = int(os.getenv("OWNER_ID", "7953454559") or 0)
SUPPORT_URL    = os.getenv("SUPPORT_URL", "https://t.me/+K_QvCsPtHPNkNTdl")

if not all([API_ID, API_HASH, BOT_TOKEN, SESSION_STRING]):
    raise SystemExit(
        "❌ Missing env vars. Please set API_ID, API_HASH, BOT_TOKEN, SESSION_STRING."
    )

# Folders
BASE_DIR      = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR    = os.path.join(BASE_DIR, "assets")
DOWNLOADS_DIR = os.path.join(os.getcwd(), "downloads")
os.makedirs(DOWNLOADS_DIR, exist_ok=True)

START_IMAGE = os.path.join(ASSETS_DIR, "start.jpg")

# ── Clients ──────────────────────────────────────────
from pyrogram import Client
from pytgcalls import PyTgCalls

bot = Client(
    "VCMusicBot",
    api_id=API_ID,
    api_hash=API_HASH,
    bot_token=BOT_TOKEN,
    in_memory=True,
)

assistant = Client(
    "VCAssistant",
    api_id=API_ID,
    api_hash=API_HASH,
    session_string=SESSION_STRING,
    in_memory=True,
)

calls = PyTgCalls(assistant)
